passenger_enabled on;
passenger_app_root /var/www/vhosts/woork.site/httpdocs;
passenger_document_root /var/www/vhosts/woork.site/httpdocs/public;
passenger_base_uri /;
passenger_app_env production;
passenger_startup_file public/index.php;