location / {
    try_files $uri $uri/ /index.php?$query_string;
}
location ~ \.php$ {
    try_files $uri =404;
    include fastcgi_params;
    fastcgi_pass "unix:/var/www/vhosts/system/$domain_name/php-fpm.sock";
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
location ~* \.(?:jpg|jpeg|png|gif|svg|css|js|woff2?)$ {
    expires 30d;
    add_header Cache-Control "public, max-age=2592000";
}
