[program:woork-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/vhosts/<domain>/httpdocs/artisan queue:work --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
numprocs=2
user=apache
redirect_stderr=true
stdout_logfile=/var/www/vhosts/<domain>/logs/queue.log
stopwaitsecs=3600
